---
title: "Data analysis"
author: "Aoyue Bi, Daxing Xu"
date: "`r Sys.Date()`"
output: 
  html_document: # html_notebook, html_document
    toc: true
    toc_float:
      toc_collapsed: true
    toc_depth: 3
    number_sections: true
    theme: simplex # default, united, cerulean, journal, flatly, darkly, readable, spacelab, united, cosmo, lumen, paper, sandstone, simplex, and yeti
    highlight: haddock # default, tango, pygments, kate, monochrome, espresso, zenburn, haddock, and breezedark
    # bibliography: bibliography.json
---


# FigS

```{r setup, echo =F, message = T, warning = F}
library(tidyverse)
# library(RColorBrewer)
library(ggpubr)
# library(egg)
## eval 代码要不要运行
## echo 代码要不要输出
## include 图要不要输出
## warning 警告要不要输出
## message 默认Bin等信息要不要输出
```

## template
```{r}
dataFile <- c("")
df <- read.delim(dataFile)
write.table(df,file="~/Documents/test.txt",quote=F,col.name=T,row.names=F,sep = "\t")
```

```{r}

#### XY axis theme
theme_classic()+
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()
      ,panel.background = element_blank()
      ,axis.line = element_line(size=0.3, colour = "black")
      ,legend.position = 'none'
      ,text = element_text(size = 12))

#### frame axis theme
theme(
    panel.background = element_blank(),
    panel.border = element_rect(colour = "black", fill=NA, size=0.7)
    ,legend.position = 'none'
    ,text = element_text(size = 12))
ggsave(p,filename = "~/Documents/test.pdf",height = 3,width = 4)

### 倾斜 45度  标签背景透明
theme(axis.text.x = element_text(vjust = 1, hjust = 1, angle = 45))
theme(strip.background = element_blank())
theme(strip.background = element_rect(size = 0.4))
```

# Fig 
## Test







 



